version: '3.4'

services:
  nginx:
    build: nginx
    image: iredmail/nginx:staging
    ports:
      - '80:80'
      - '443:443'

  iredadmin:
    build: iredadmin
    image: iredmail/iredadmin:staging

  roundcube:
    build: roundcube
    image: iredmail/roundcube:staging

  memcached:
    image: memcached:1.5.4

  postfix:
    build: postfix
    image: iredmail/postfix:staging
    ports:
      - '25:25'
      - '587:587'

  iredapd:
    build: iredapd
    image: iredmail/iredapd:staging

  amavisd:
    build: amavisd
    image: iredmail/amavisd:staging

  spamassassin:
    build: spamassassin
    image: iredmail/spamassassin:staging

  clamav:
    build: clamav
    image: iredmail/clamav:staging

  dovecot:
    build: dovecot
    image: iredmail/dovecot:staging
    ports:
      - '110:110'
      - '143:143'
      - '993:993'
      - '995:995'
